In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
array = np.array(my_list)

In [4]:
np.arrange(0,11,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [7]:
np.linspace(0,11,100)

array([  0.        ,   0.11111111,   0.22222222,   0.33333333,
         0.44444444,   0.55555556,   0.66666667,   0.77777778,
         0.88888889,   1.        ,   1.11111111,   1.22222222,
         1.33333333,   1.44444444,   1.55555556,   1.66666667,
         1.77777778,   1.88888889,   2.        ,   2.11111111,
         2.22222222,   2.33333333,   2.44444444,   2.55555556,
         2.66666667,   2.77777778,   2.88888889,   3.        ,
         3.11111111,   3.22222222,   3.33333333,   3.44444444,
         3.55555556,   3.66666667,   3.77777778,   3.88888889,
         4.        ,   4.11111111,   4.22222222,   4.33333333,
         4.44444444,   4.55555556,   4.66666667,   4.77777778,
         4.88888889,   5.        ,   5.11111111,   5.22222222,
         5.33333333,   5.44444444,   5.55555556,   5.66666667,
         5.77777778,   5.88888889,   6.        ,   6.11111111,
         6.22222222,   6.33333333,   6.44444444,   6.55555556,
         6.66666667,   6.77777778,   6.88888889,   7.  

In [8]:
np.linspace(0,1,0.1)

/Users/amandazhu/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/ipykernel_launcher.py:1: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  """Entry point for launching an IPython kernel.


array([], dtype=float64)

In [12]:
np.random.randint(1,5)

4

In [13]:
np.random.seed(101)

In [14]:
np.random.seed(101)
np.random.randint(1,100,10)

array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41])

In [15]:
np.random.randint(1,100,10)


array([ 5, 64, 41, 61, 93, 65,  6, 13, 94, 41])

In [16]:
arr = np.random.randint(0,10)

In [17]:
arr.max()

AttributeError: 'int' object has no attribute 'max'

In [18]:
arr

1

In [19]:
arr = np.random.randint(1,10,4)

In [20]:
arr

array([4, 9, 4, 4])

In [21]:
arr.max()

9

In [22]:
mat = np.arange(0,100).reshape(10,10)

In [23]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
mat[1,2]

12

In [25]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
mat[0:3, 2:4]

array([[ 2,  3],
       [12, 13],
       [22, 23]])

In [27]:
mat > 50


array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [28]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
import pandas as pd


In [30]:
pwd


'/Users/amandazhu/GitHub/TensorFlow-Electricity-Load-Prediction/TensorFlow/Tensorflow-Bootcamp-master '

In [32]:
df = pd.read_csv('00-Crash-Course-Basics/salaries.csv')

In [33]:
df

Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27

In [36]:
df[['Name', 'Salary']]

Name  Salary
0    John   50000
1   Sally  120000
2  Alyssa   80000

In [38]:
df.describe()

Salary        Age
count       3.000000   3.000000
mean    83333.333333  35.333333
std     35118.845843   9.073772
min     50000.000000  27.000000
25%     65000.000000  30.500000
50%     80000.000000  34.000000
75%    100000.000000  39.500000
max    120000.000000  45.000000

In [39]:
df['Salary'] > 60000

0    False
1     True
2     True
Name: Salary, dtype: bool

In [41]:
df[df['Salary'] > 60000]

Name  Salary  Age
1   Sally  120000   45
2  Alyssa   80000   27